### ISSUE TITLE
Child process exits with error when using MPI with a psydac import

### ISSUE THREAD

**Issue by spossann** [pyccel/psydac#344]
I want to launch a parallel program using `subprocess.run(['mpirun', ...])`. This works fine in general. However, when adding a psydac import the child process fails with exit code 1.

Here is a minimal example:

```
# hello.py
print('Hello world.')

# test_subproc.py
import subprocess

from psydac.linalg.basic import Vector

subprocess.run(['mpirun',
                '-n',
                '1',
                'python3',
                'hello.py'], check=True)
```
Running `python3 test_subproc.py` yields
```
Traceback (most recent call last):
  File "/home/spossann/git_repos/struphy/src/struphy/test_subproc.py", line 5, in <module>
    subprocess.run([
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mpirun', '-n', '1', 'python3', 'hello.py']' returned non-zero exit status 1.

```
When removing the psydac import, it works fine:
```
# test_subproc.py
import subprocess

subprocess.run(['mpirun',
                '-n',
                '1',
                'python3',
                'hello.py'], check=True)
```
yields
```
Hello world.
```
Note that it works with the psydac import if I don't use MPI:
```
# test_subproc.py
import subprocess

from psydac.linalg.basic import Vector

subprocess.run(['python3',  'hello.py'], check=True)
```
yields
```
Hello world.
```
I also tested this with other psydac imports such as  `from psydac.feec import derivatives` and the error seems robust.

**Comment by yguclu** [comment]
Have you tried to use `subprocess` together with `mpi4py`?

**Comment by yguclu** [comment]
What I mean is replacing
```python
from psydac.linalg.basic import Vector
```
with
```python
from mpi4py import MPI
```

**Comment by spossann** [comment]
Apparently, it is not possible to call `subprocess.run(['mpirun' ...)` that calls `mpirun` when a `MPI.COMM_WORLD` already exists.
