### ISSUE TITLE
Fix bug regarding the norm of a cross-product of two functions

### ISSUE THREAD

**Issue by jowezarek** [pyccel/psydac#351]
When trying to compute the L2-norm of the cross product `J x H` on the unit cube, with `J, H` both being three-dimensional vectors fields belonging to `V1 = Hcurl`, an Assertion error is raised.

Example code looks like this:
```
J, H = elements_of(derham.V1, names='J, H')

expr = Cross_3d(J, H)
# or alternatively
# expr = cross(J, H)

l2_norm_JxH = Norm(expr, domain, kind='l2')
l2_norm_JxH_h = discretize(l2_norm_JxH, domain_h, derham_h.V1, backend=backend)
```

The error message reads:
```
Traceback (most recent call last):
  File "/home/jubuntu/Dokumente/psydac_gitlab/psydac/psydac/api/beltrami/norm_test.py", line 65, in <module>
    l2_norm_JxH_h = discretize(l2_norm_JxH, domain_h, derham_h.V1, backend=backend)
  File "/home/jubuntu/Dokumente/psydac_gitlab/psydac/psydac/api/discretization.py", line 473, in discretize
    return DiscreteFunctional(a, kernel_expr, *args, **kwargs)
  File "/home/jubuntu/Dokumente/psydac_gitlab/psydac/psydac/api/fem.py", line 1426, in __init__
    BasicDiscrete.__init__(self, expr, kernel_expr, comm=comm, root=0, discrete_space=discrete_space,
  File "/home/jubuntu/Dokumente/psydac_gitlab/psydac/psydac/api/basic.py", line 297, in __init__
    BasicCodeGen.__init__(self, expr, folder=folder, comm=comm, root=root, discrete_space=discrete_space,
  File "/home/jubuntu/Dokumente/psydac_gitlab/psydac/psydac/api/basic.py", line 108, in __init__
    ast = self._create_ast( expr=expr, tag=tag, discrete_space=discrete_space,
  File "/home/jubuntu/Dokumente/psydac_gitlab/psydac/psydac/api/basic.py", line 338, in _create_ast
    return AST(expr, kernel_expr, discrete_space, mapping_space=mapping_space,
  File "/home/jubuntu/Dokumente/psydac_gitlab/psydac/psydac/api/ast/fem.py", line 335, in __init__
    fields_degrees      = get_degrees(fields, spaces)
  File "/home/jubuntu/Dokumente/psydac_gitlab/psydac/psydac/api/ast/fem.py", line 227, in get_degrees
    assert len(funcs) == len(degrees)
AssertionError
```

More information about `funcs` and `degrees`:
`len(funcs): 6, (H[0], H[1], H[2], J[0], J[1], J[2]), len(degrees): 3`

**Comment by yguclu** [comment]
@jowezarek Do we still get an `AssertionError` here?

**Comment by jowezarek** [comment]
@yguclu Yes we still get an `AssertionError` here. I just updated the bug description such that it includes a minimal working example. I however wonder whether this is actually a `Cross_3d`/`Cross`/`cross`-issue, or whether `Norm` was never intended to work with more than one unknown. In that case, I suppose we can close this issue, and only once this feature is required, we can think about including it.

**Comment by yguclu** [comment]
@jowezarek Thanks for the example! I think that `Norm` was intended to work generally, but was only partially implemented. Here the underlying issue seems to be that `Cross` does not return something well-defined like a `Vector` object. This is a problem in SymPDE which will be addressed as part of its [new API design](https://github.com/orgs/pyccel/projects/8/views/1) and in particular issue pyccel/sympde#150.
